import { test, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { buildIndex, type LookupTable } from './schema';

const HEAD = '<!-- semantic-zoom:payload:v1';
const TAIL = '-->';

function extract(src: string): string {
  const start = src.lastIndexOf(HEAD);
  const jsonStart = start + HEAD.length;
  const end = src.slice(jsonStart).lastIndexOf(TAIL) + jsonStart;
  return src.slice(jsonStart, end).trim();
}

function normalize(v: unknown): unknown {
  if (Array.isArray(v)) return v.map(normalize);
  if (v && typeof v === 'object') {
    return Object.fromEntries(
      Object.entries(v as Record<string, unknown>)
        .sort(([a], [b]) => a.localeCompare(b))
        .map(([k, val]) => [k, normalize(val)]),
    );
  }
  return v;
}

test('TS parse of fixture payload structurally equals Rust canonical parse', () => {
  const src = readFileSync(
    new URL('../../fixtures/zoom_test.md', import.meta.url),
    'utf8',
  );
  const tsTable = JSON.parse(extract(src)) as LookupTable;

  let rustCanonRaw: string;
  try {
    rustCanonRaw = readFileSync(
      new URL('../../fixtures/roundtrip-expected.json', import.meta.url),
      'utf8',
    );
  } catch {
    throw new Error(
      'fixtures/roundtrip-expected.json is missing. It is a DERIVED artifact ' +
        'generated by the Rust round-trip test. Run `cd src-tauri && cargo test --test roundtrip` first.',
    );
  }
  const rustCanon = JSON.parse(rustCanonRaw);

  // Both Rust (serde rename = "docHash") and TS use camelCase `docHash`,
  // so a single key-order-independent structural comparison suffices.
  expect(normalize(tsTable)).toEqual(normalize(rustCanon));
  expect(() => buildIndex(tsTable)).not.toThrow();
});
